import { Table, Relation, DatabaseType } from '@/types/schema';

export const generateSampleECommerceSchema = (databaseType: DatabaseType): { tables: Table[], relations: Relation[] } => {
  const tables: Table[] = [
    {
      id: 'users-table',
      name: 'users',
      position: { x: 100, y: 100 },
      color: '#3B82F6',
      description: 'User accounts and authentication',
      columns: [
        {
          id: 'users-id',
          name: 'id',
          type: databaseType === 'postgresql' ? 'SERIAL' : 'INT',
          isPrimary: true,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: true,
        },
        {
          id: 'users-email',
          name: 'email',
          type: 'VARCHAR(255)',
          isPrimary: false,
          isForeign: false,
          isUnique: true,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'users-password',
          name: 'password_hash',
          type: 'VARCHAR(255)',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'users-name',
          name: 'full_name',
          type: 'VARCHAR(255)',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'users-created',
          name: 'created_at',
          type: databaseType === 'postgresql' ? 'TIMESTAMP' : 'DATETIME',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
          defaultValue: 'CURRENT_TIMESTAMP',
        },
      ],
      indexes: [
        {
          id: 'users-email-idx',
          name: 'idx_users_email',
          columns: ['email'],
          isUnique: true,
        },
      ],
      constraints: [],
    },
    {
      id: 'products-table',
      name: 'products',
      position: { x: 500, y: 100 },
      color: '#10B981',
      description: 'Product catalog',
      columns: [
        {
          id: 'products-id',
          name: 'id',
          type: databaseType === 'postgresql' ? 'SERIAL' : 'INT',
          isPrimary: true,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: true,
        },
        {
          id: 'products-name',
          name: 'name',
          type: 'VARCHAR(255)',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'products-description',
          name: 'description',
          type: 'TEXT',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: true,
          isAutoIncrement: false,
        },
        {
          id: 'products-price',
          name: 'price',
          type: 'DECIMAL(10,2)',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'products-stock',
          name: 'stock_quantity',
          type: 'INT',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
          defaultValue: '0',
        },
        {
          id: 'products-category',
          name: 'category_id',
          type: 'INT',
          isPrimary: false,
          isForeign: true,
          isUnique: false,
          isNullable: true,
          isAutoIncrement: false,
        },
      ],
      indexes: [
        {
          id: 'products-category-idx',
          name: 'idx_products_category',
          columns: ['category_id'],
          isUnique: false,
        },
      ],
      constraints: [],
    },
    {
      id: 'categories-table',
      name: 'categories',
      position: { x: 800, y: 100 },
      color: '#F59E0B',
      description: 'Product categories',
      columns: [
        {
          id: 'categories-id',
          name: 'id',
          type: databaseType === 'postgresql' ? 'SERIAL' : 'INT',
          isPrimary: true,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: true,
        },
        {
          id: 'categories-name',
          name: 'name',
          type: 'VARCHAR(100)',
          isPrimary: false,
          isForeign: false,
          isUnique: true,
          isNullable: false,
          isAutoIncrement: false,
        },

      ],
      indexes: [],
      constraints: [],
    },
    {
      id: 'orders-table',
      name: 'orders',
      position: { x: 100, y: 400 },
      color: '#EF4444',
      description: 'Customer orders',
      columns: [
        {
          id: 'orders-id',
          name: 'id',
          type: databaseType === 'postgresql' ? 'SERIAL' : 'INT',
          isPrimary: true,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: true,
        },
        {
          id: 'orders-user',
          name: 'user_id',
          type: 'INT',
          isPrimary: false,
          isForeign: true,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'orders-total',
          name: 'total_amount',
          type: 'DECIMAL(10,2)',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'orders-status',
          name: 'status',
          type: databaseType === 'postgresql' ? 'VARCHAR(20)' : 'VARCHAR(20)',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
          defaultValue: 'pending',
        },
        {
          id: 'orders-created',
          name: 'created_at',
          type: databaseType === 'postgresql' ? 'TIMESTAMP' : 'DATETIME',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
          defaultValue: 'CURRENT_TIMESTAMP',
        },
      ],
      indexes: [
        {
          id: 'orders-user-idx',
          name: 'idx_orders_user',
          columns: ['user_id'],
          isUnique: false,
        },
      ],
      constraints: [],
    },
    {
      id: 'order-items-table',
      name: 'order_items',
      position: { x: 500, y: 400 },
      color: '#8B5CF6',
      description: 'Items within orders',
      columns: [
        {
          id: 'order-items-id',
          name: 'id',
          type: databaseType === 'postgresql' ? 'SERIAL' : 'INT',
          isPrimary: true,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: true,
        },
        {
          id: 'order-items-order',
          name: 'order_id',
          type: 'INT',
          isPrimary: false,
          isForeign: true,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'order-items-product',
          name: 'product_id',
          type: 'INT',
          isPrimary: false,
          isForeign: true,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'order-items-quantity',
          name: 'quantity',
          type: 'INT',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
        {
          id: 'order-items-price',
          name: 'unit_price',
          type: 'DECIMAL(10,2)',
          isPrimary: false,
          isForeign: false,
          isUnique: false,
          isNullable: false,
          isAutoIncrement: false,
        },
      ],
      indexes: [
        {
          id: 'order-items-order-idx',
          name: 'idx_order_items_order',
          columns: ['order_id'],
          isUnique: false,
        },
        {
          id: 'order-items-product-idx',
          name: 'idx_order_items_product',
          columns: ['product_id'],
          isUnique: false,
        },
      ],
      constraints: [],
    },
  ];

  const relations: Relation[] = [
    {
      id: 'rel-products-categories',
      fromTableId: 'categories-table',
      toTableId: 'products-table',
      fromColumnId: 'categories-id',
      toColumnId: 'products-category',
      type: '1:N',
      onDelete: 'SET NULL',
      onUpdate: 'CASCADE',
      name: 'product_category',
    },

    {
      id: 'rel-orders-users',
      fromTableId: 'users-table',
      toTableId: 'orders-table',
      fromColumnId: 'users-id',
      toColumnId: 'orders-user',
      type: '1:N',
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
      name: 'order_user',
    },
    {
      id: 'rel-order-items-orders',
      fromTableId: 'orders-table',
      toTableId: 'order-items-table',
      fromColumnId: 'orders-id',
      toColumnId: 'order-items-order',
      type: '1:N',
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
      name: 'order_item_order',
    },
    {
      id: 'rel-order-items-products',
      fromTableId: 'products-table',
      toTableId: 'order-items-table',
      fromColumnId: 'products-id',
      toColumnId: 'order-items-product',
      type: '1:N',
      onDelete: 'RESTRICT',
      onUpdate: 'CASCADE',
      name: 'order_item_product',
    },
  ];

  return { tables, relations };
};